#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	static int speed = 50, m_speed = -50, slow_speed = 20, slow_m_speed = -20;

	motor[motorE] = 0;
	motor[motorD] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
	servo[servo1] = 127;



	while (joy1Btn(10) != 1)
		getJoystickSettings(joystick);


	while(true)
	{
		getJoystickSettings(joystick);

		while (joy1Btn (7)) /* turn left */
		{
			getJoystickSettings(joystick);

			motor[motorE] = speed;
			motor[motorD] = speed;
			motor[motorF] = speed;
			motor[motorG] = speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joy1Btn (8)) /* turn right*/
		{
			////getJoystickSettings(joystick);

			motor[motorE] = m_speed;
			motor[motorD] = m_speed;
			motor[motorF] = m_speed;
			motor[motorG] = m_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joy1Btn (4)) /* move forward*/
		{
			////getJoystickSettings(joystick);
			motor[motorE] = m_speed;
			motor[motorD] = m_speed;
			motor[motorF] = speed;
			motor[motorG] = speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joy1Btn (2)) /* move backward */
		{
			////getJoystickSettings(joystick);
			motor[motorE] = speed;
			motor[motorD] = speed;
			motor[motorF] = m_speed;
			motor[motorG] = m_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joy1Btn (1)) /* move left */
		{
			////getJoystickSettings(joystick);
			motor[motorE] = speed;
			motor[motorD] = m_speed;
			motor[motorF] = m_speed;
			motor[motorG] = speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joy1Btn (3)) /* move right */
		{
			////getJoystickSettings(joystick);

			motor[motorE] = m_speed;
			motor[motorD] = speed;
			motor[motorF] = speed;
			motor[motorG] = m_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joystick.joy1_TopHat == 0) /* slow move forward */
		{
			////getJoystickSettings(joystick);

			motor[motorE] = slow_m_speed;
			motor[motorD] = slow_m_speed;
			motor[motorF] = slow_speed;
			motor[motorG] = slow_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joystick.joy1_TopHat == 4) /* slow move backward */
		{
			////getJoystickSettings(joystick);

			motor[motorE] = slow_speed;
			motor[motorD] = slow_speed;
			motor[motorF] = slow_m_speed;
			motor[motorG] = slow_m_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joystick.joy1_TopHat == 6) /* slow move left */
		{
			////getJoystickSettings(joystick);

			motor[motorE] = slow_speed;
			motor[motorD] = slow_m_speed;
			motor[motorF] = slow_m_speed;
			motor[motorG] = slow_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		////getJoystickSettings(joystick);

		while (joystick.joy1_TopHat == 2) /* slow move right */
		{
			////getJoystickSettings(joystick);

			motor[motorE] = slow_m_speed;
			motor[motorD] = slow_speed;
			motor[motorF] = slow_speed;
			motor[motorG] = slow_m_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		//getJoystickSettings(joystick);

		while (joy1Btn (6)) /* slow turn right*/
		{
			////getJoystickSettings(joystick);

			motor[motorE] = slow_m_speed;
			motor[motorD] = slow_m_speed;
			motor[motorF] = slow_m_speed;
			motor[motorG] = slow_m_speed;
		}

		while (joy1Btn (5)) /* slow turn left */
		{
			getJoystickSettings(joystick);

			motor[motorE] = slow_speed;
			motor[motorD] = slow_speed;
			motor[motorF] = slow_speed;
			motor[motorG] = slow_speed;
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;

		while (joy1Btn (9))
		{
			//getJoystickSettings(joystick);
			servo[servo1] = 0; /* 0 - Full Power/ Speed Reverse; 127 - Stop; 256 - Full Power/ Speed Forward */
		}

		motor[motorE] = 0;
		motor[motorD] = 0;
		motor[motorF] = 0;
		motor[motorG] = 0;
		servo[servo1] = 127;
	}
}
